[project]
name="src"
version="0.0.1"
description="An MLOps project for productionaizing models"
authors = [{name="Debanjan Chowdhury", email="debanjanchowdhury900@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}